Repository esa-tu-darmstadt/tapasco, pull requests merged in 2019-10, with the labels that each got.

#132 Make Vivado timeout configurable per platform
  toolflow/scala/src/main/scala/tapasco/activity/composers/VivadoComposer.scala
  toolflow/scala/src/main/scala/tapasco/base/Platform.scala
  toolflow/scala/src/main/scala/tapasco/base/json/package.scala
  toolflow/scala/src/main/scala/tapasco/parser/Usage.scala
  toolflow/scala/src/test/resources/json-examples/correct-platform.json
  toolflow/scala/src/test/scala/tapasco/base/PlatformTest.scala
Labels: Change Request, enhancement

#129 Make the maximum DSE frequency configurable as a single value in the platform JSON
  toolflow/scala/src/main/scala/tapasco/base/Platform.scala
  toolflow/scala/src/main/scala/tapasco/base/json/package.scala
  toolflow/scala/src/test/resources/json-examples/correct-platform.json
  toolflow/scala/src/test/resources/json-examples/unknown-platform.json
  toolflow/scala/src/test/scala/tapasco/base/PlatformTest.scala
Labels: Change Request, enhancement

#134 Correctly notify ReportManager of changes to the basepath
  toolflow/scala/src/main/scala/tapasco/filemgmt/FileAssetManager.scala
  toolflow/scala/src/main/scala/tapasco/filemgmt/ReportManager.scala
Labels: bug

#135 Create OS packages for the TaPaSCo toolflow
  .gitlab-ci.yml
  toolflow/os-package/setup.sh
  toolflow/scala/build.gradle
  toolflow/scala/src/main/scala/tapasco/Common.scala
  toolflow/scala/src/main/scala/tapasco/filemgmt/BasePathManager.scala
  toolflow/scala/src/main/scala/tapasco/package.scala
  toolflow/vivado/platform/common/addressmap.tcl
Labels: Feature Request, enhancement

#136 Follow symlinks for finding kernel.json Files
  toolflow/scala/src/main/scala/tapasco/filemgmt/EntityCache.scala
Labels: bug
