Repository esa-tu-darmstadt/tapasco, pull requests merged in 2020-04, with the labels that each got.

#167 Generate valid DSE directory names
  toolflow/scala/src/main/scala/tapasco/task/DesignSpaceExplorationTask.scala
Labels: bug

#124 Add Amazon AWS F1 as target platform
  runtime/examples/tapasco-debug/debug-screens/BlueDebugScreen.hpp
  runtime/kernel/pcie/pcie.c
  runtime/kernel/pcie/pcie.h
  runtime/kernel/pcie/pcie_device.c
  runtime/kernel/pcie/pcie_device.h
  runtime/kernel/pcie/pcie_irq.c
  runtime/kernel/pcie/pcie_irq.h
  runtime/kernel/tlkm/tlkm_platform.c
  runtime/platform/include/platform_caps.h
  runtime/platform/include/platform_components.h
  toolflow/bin/afihelper
  toolflow/bin/afilist
  toolflow/vivado/arch/axi4mm/axi4mm.tcl
  toolflow/vivado/common/common_ip.tcl
  toolflow/vivado/common/design.master.tcl.template
  toolflow/vivado/common/hls.tcl.template
  toolflow/vivado/common/ip.tcl
  toolflow/vivado/common/ip/AWSIntrCtrl/component.xml
  toolflow/vivado/common/ip/AWSIntrCtrl/constraints/msix_intr_ctrl.xdc
  toolflow/vivado/common/ip/AWSIntrCtrl/src/FIFO2.v
  toolflow/vivado/common/ip/AWSIntrCtrl/src/SizedFIFO.v
  toolflow/vivado/common/ip/AWSIntrCtrl/src/SyncPulse.v
  toolflow/vivado/common/ip/AWSIntrCtrl/src/mkAWSIntrCtrl.v
  toolflow/vivado/common/ip/AWSIntrCtrl/xgui/AWSIntrCtrl_v1_0.tcl
  toolflow/vivado/common/ip/AWSIntrCtrl/xgui/mkAWSIntrCtrl_v1_0.tcl
  toolflow/vivado/common/ip/BlueDMA_256_512_32/component.xml
  toolflow/vivado/common/ip/BlueDMA_256_512_32/src/mkBlueDMAVivado.v
  toolflow/vivado/common/ip/BlueDMA_512_512_64/component.xml
  toolflow/vivado/common/ip/BlueDMA_512_512_64/src/mkBlueDMAVivado.v
  toolflow/vivado/platform/aws/aws.benchmark
  toolflow/vivado/platform/aws/aws.tcl
  toolflow/vivado/platform/aws/constraints/125/aws_gen_clk_constraints.tcl
  toolflow/vivado/platform/aws/constraints/125/cl_clocks_aws.xdc
  toolflow/vivado/platform/aws/constraints/250/aws_gen_clk_constraints.tcl
  toolflow/vivado/platform/aws/constraints/250/cl_clocks_aws.xdc
  toolflow/vivado/platform/aws/include/platform_aws.h
  toolflow/vivado/platform/aws/opt_design_post.tcl
  toolflow/vivado/platform/aws/opt_design_pre.tcl
  toolflow/vivado/platform/aws/place_design_post.tcl
  toolflow/vivado/platform/aws/platform.json
  toolflow/vivado/platform/aws/plugins/print_version.tcl
  toolflow/vivado/platform/aws/route_design_post.tcl
  toolflow/vivado/platform/common/platform.tcl
Labels: Refactoring, enhancement

#171 Run OOC evaluation before DSE
  toolflow/scala/src/main/scala/tapasco/activity/Import.scala
  toolflow/scala/src/main/scala/tapasco/jobs/executors/DesignSpaceExploration.scala
Labels: enhancement

#177 Correctly signal Vivado errors
  toolflow/scala/src/main/scala/tapasco/activity/composers/ComposerLog.scala
  toolflow/scala/src/main/scala/tapasco/activity/composers/VivadoComposer.scala
  toolflow/scala/src/main/scala/tapasco/jobs/executors/HighLevelSynthesis.scala
Labels: bug

#172 Correctly detect Vivado failure
  toolflow/scala/src/main/scala/tapasco/activity/composers/VivadoComposer.scala
Labels: bug

#173 Make file extension of the compose output configurable per platform
  toolflow/scala/src/main/scala/tapasco/activity/composers/VivadoComposer.scala
  toolflow/scala/src/main/scala/tapasco/base/Platform.scala
  toolflow/scala/src/main/scala/tapasco/base/json/package.scala
  toolflow/scala/src/main/scala/tapasco/task/ComposeTask.scala
Labels: enhancement
